name: ci

on: [push, pull_request]

jobs:
  deno-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno test -A
  node-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "23.6.0"
      - run: npm install
      - run: npm run build
      - run: cd examples && npm install
      - run: node --test
